spring :
  data :
    mongodb :
      username               : admin
      password               : admin
      authentication-database: admin
      host                   : 127.0.0.1
      port                   : 27017
      database               : test
